on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install pip requirements and pyinstaller
      run: pip install -r requirements.txt pyinstaller

    - name: Build binary
      run: pyinstaller -F -n vidscaler vidscaler/__main__.py

    - name: Compress binary
      uses: svenstaro/upx-action@v2
      with:
        files: dist/vidscaler
        args: --best --lzma
        strip: true

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/vidscaler
